### ISSUE TITLE
There are two bugs on source.

### ISSUE THREAD

**Issue by miky2k** [sittisaks/rt5350-i2c#1]
from original there is :

 rt_i2c_w32(rem - 1, REG_BYTECNT_REG);
 rt_i2c_w32(READ_CMD, REG_STARTXFR_REG);

shold be written as

if (rem) {
    rt_i2c_w32(rem - 1, REG_BYTECNT_REG);
    rt_i2c_w32(READ_CMD, REG_STARTXFR_REG);
}

and in your implementation :

```
        if ((ret=rt_i2c_wait_rx_done())<0)                return ret;
        if ((ret=rt_i2c_get_ack())<0)                return ret;
```

should be

```
         if (rt_i2c_wait_rx_done()<0) ret = rt_i2c_wait_rx_done();
         if (rt_i2c_get_ack()<0)      ret = rt_i2c_get_ack();
```

because you cannot stop and exit a cycle if you load REG_DATAOUT_REG without
send correct number of bytes (it hang i2c state machine).

**Comment by sittisaks** [comment]
Changed the code per recommendation from https://forum.openwrt.org/viewtopic.php?pid=248140
